version: '3.8'

services:
  ollama:
    build: ./ollama
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped

  app:
    build: ./app
    container_name: bio-rag-app
    depends_on:
      - ollama
    volumes:
      - ./data:/app/data                 # Monte le CSV
      - ./chroma_db_fresh:/app/chroma_db # 🔥 Monte UNIQUEMENT le dossier fresh
      - ./app:/app                       # Pour le Live Coding (synchronisation du code)
    environment:
      - OLLAMA_HOST=http://ollama:11434  # Tableau blanc
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  ollama_data: